### ISSUE TITLE
Recovering gracefully from UnrecognizedFormat

### ISSUE THREAD

**Issue by yuvadm** [aschey/icy-metadata#23]
Sometimes when attaching an `IcyMetadataReader` to a rodio `Decoder` an `UnrecognizedFormat` error is thrown.

e.g https://github.com/yuvadm/somafm.rs/blob/bcb69f9afa402d747be9feaf7224db6f53680d8c/src/audio/rodio.rs#L59 might throw:

```thread 'main' panicked at src/audio/rodio.rs:59:51:
called `Result::unwrap()` on an `Err` value: UnrecognizedFormat
```

I'm assuming this is due to some network race condition where the stream might not have been initialized yet.

Is there a better way to initialize the reader/decoder in this case to avoid these intermittent failures?

**Comment by aschey** [comment]
Oh nevermind, I just noticed you only have `symphonia-mp3` enabled so it probably isn't a format detection error, but it could be another bug in the decoder.

**Comment by yuvadm** [comment]
Yeah just looping on the init was the obvious choice, I was hoping for something more sophisticated, or some other way to init the decoder, but oh well :) thanks!
